name: check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"


jobs:

  check:

    runs-on: ubuntu-latest


    steps:

    - name: checkout
      uses: actions/checkout@v4


    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22


    - name: run monitor
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      run: |
        node monitor.js
